<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-06-16 17:21

$extensionPath = t3lib_extMgm::extPath('upgradereport');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_upgradereport_checks_abstractcheckdefinition' => $extensionClassesPath . 'Checks/AbstractCheckDefinition.php',
	'tx_upgradereport_checks_core_xclasses_definition' => $extensionClassesPath . 'Checks/Core/Xclasses/Processor.php',
	'tx_upgradereport_checks_core_xclasses_resultanalyzer' => $extensionClassesPath . 'Checks/Core/Xclasses/ResultAnalyzer.php',
	'tx_upgradereport_controller_abstractcontroller' => $extensionClassesPath . 'Controller/AbstractController.php',
	'tx_upgradereport_controller_reportcontroller' => $extensionClassesPath . 'Controller/ReportController.php',
	'tx_upgradereport_domain_interface_check' => $extensionClassesPath . 'Domain/Interface/Check.php',
	'tx_upgradereport_domain_interface_checkdescription' => $extensionClassesPath . 'Domain/Interface/CheckDescription.php',
	'tx_upgradereport_domain_interface_checkprocessor' => $extensionClassesPath . 'Domain/Interface/CheckProcessor.php',
	'tx_upgradereport_domain_interface_checkrequirements' => $extensionClassesPath . 'Domain/Interface/CheckRequirements.php',
	'tx_upgradereport_domain_interface_resultanalyzer' => $extensionClassesPath . 'Domain/Interface/CheckResultAnalyzer.php',
	'tx_upgradereport_domain_interface_issuedetails' => $extensionClassesPath . 'Domain/Interface/IssueDetails.php',
	'tx_upgradereport_domain_model_issue' => $extensionClassesPath . 'Domain/Model/Issue.php',
	'tx_upgradereport_service_check_registry' => $extensionClassesPath . 'Service/Check/Registry.php',
	'tx_upgradereport_service_check_requirementsanalyzer' => $extensionClassesPath . 'Service/Check/RequirementsAnalyzer.php',
);
?>