<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-06-15 11:12

$extensionPath = t3lib_extMgm::extPath('upgradereport');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_upgradereport_controller_abstractcontroller' => $extensionClassesPath . 'Controller/AbstractController.php',
	'tx_upgradereport_controller_reportcontroller' => $extensionClassesPath . 'Controller/ReportController.php',
);
?>