<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-07-02 14:48

$extensionPath = t3lib_extMgm::extPath('smoothmigration');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_smoothmigration_checks_abstractcheckdefinition' => $extensionClassesPath . 'Checks/AbstractCheckDefinition.php',
	'tx_smoothmigration_checks_core_requireonceinextensions_definition' => $extensionClassesPath . 'Checks/Core/RequireOnceInExtensions/Definition.php',
	'tx_smoothmigration_checks_core_requireonceinextensions_processor' => $extensionClassesPath . 'Checks/Core/RequireOnceInExtensions/Processor.php',
	'tx_smoothmigration_checks_core_requireonceinextensions_resultanalyzer' => $extensionClassesPath . 'Checks/Core/RequireOnceInExtensions/ResultAnalyzer.php',
	'tx_smoothmigration_checks_core_xclasses_definition' => $extensionClassesPath . 'Checks/Core/Xclasses/Definition.php',
	'tx_smoothmigration_checks_core_xclasses_processor' => $extensionClassesPath . 'Checks/Core/Xclasses/Processor.php',
	'tx_smoothmigration_checks_core_xclasses_resultanalyzer' => $extensionClassesPath . 'Checks/Core/Xclasses/ResultAnalyzer.php',
	'tx_smoothmigration_checks_core_calltodeprecatedstaticmethods_definition' => $extensionClassesPath . 'Checks/Core/CallToDeprecatedStaticMethods/Definition.php',
	'tx_smoothmigration_checks_core_calltodeprecatedstaticmethods_processor' => $extensionClassesPath . 'Checks/Core/CallToDeprecatedStaticMethods/Processor.php',
	'tx_smoothmigration_checks_core_calltodeprecatedstaticmethods_resultanalyzer' => $extensionClassesPath . 'Checks/Core/CallToDeprecatedStaticMethods/ResultAnalyzer.php',
	'tx_smoothmigration_checks_core_calltodeprecatedviewhelpers_definition' => $extensionClassesPath . 'Checks/Core/CallToDeprecatedViewHelpers/Definition.php',
	'tx_smoothmigration_checks_core_calltodeprecatedviewhelpers_processor' => $extensionClassesPath . 'Checks/Core/CallToDeprecatedViewHelpers/Processor.php',
	'tx_smoothmigration_checks_core_calltodeprecatedviewhelpers_resultanalyzer' => $extensionClassesPath . 'Checks/Core/CallToDeprecatedViewHelpers/ResultAnalyzer.php',
	'tx_smoothmigration_checks_core_mysql_definition' => $extensionClassesPath . 'Checks/Core/Mysql/Definition.php',
	'tx_smoothmigration_checks_core_mysql_processor' => $extensionClassesPath . 'Checks/Core/Mysql/Processor.php',
	'tx_smoothmigration_checks_core_mysql_resultanalyzer' => $extensionClassesPath . 'Checks/Core/Mysql/ResultAnalyzer.php',
	'tx_smoothmigration_controller_abstractmodulecontroller' => $extensionClassesPath . 'Controller/AbstractModuleController.php',
	'tx_smoothmigration_controller_ajaxcontroller' => $extensionClassesPath . 'Controller/AjaxController.php',
	'tx_smoothmigration_controller_reportcontroller' => $extensionClassesPath . 'Controller/ReportController.php',
	'tx_smoothmigration_domain_interface_check' => $extensionClassesPath . 'Domain/Interface/Check.php',
	'tx_smoothmigration_domain_interface_checkdescription' => $extensionClassesPath . 'Domain/Interface/CheckDescription.php',
	'tx_smoothmigration_domain_interface_checkprocessor' => $extensionClassesPath . 'Domain/Interface/CheckProcessor.php',
	'tx_smoothmigration_domain_interface_checkrequirements' => $extensionClassesPath . 'Domain/Interface/CheckRequirements.php',
	'tx_smoothmigration_domain_interface_resultanalyzer' => $extensionClassesPath . 'Domain/Interface/CheckResultAnalyzer.php',
	'tx_smoothmigration_domain_interface_issuelocation' => $extensionClassesPath . 'Domain/Interface/IssueLocation.php',
	'tx_smoothmigration_domain_model_issue' => $extensionClassesPath . 'Domain/Model/Issue.php',
	'tx_smoothmigration_domain_model_issuelocation_configuration' => $extensionClassesPath . 'Domain/Model/IssueLocation/Configuration.php',
	'tx_smoothmigration_domain_model_issuelocation_database' => $extensionClassesPath . 'Domain/Model/IssueLocation/Database.php',
	'tx_smoothmigration_domain_model_issuelocation_file' => $extensionClassesPath . 'Domain/Model/IssueLocation/File.php',
	'tx_smoothmigration_domain_model_issuelocation_physicallocation' => $extensionClassesPath . 'Domain/Model/IssueLocation/PhysicalLocation.php',
	'tx_smoothmigration_domain_repository_issuerepository' => $extensionClassesPath . 'Domain/Repository/IssueRepository.php',
	'tx_smoothmigration_service_filelocatorservice' => $extensionClassesPath . 'Service/FileLocatorService.php',
	'tx_smoothmigration_service_check_registry' => $extensionClassesPath . 'Service/Check/Registry.php',
	'tx_smoothmigration_service_check_requirementsanalyzer' => $extensionClassesPath . 'Service/Check/RequirementsAnalyzer.php',
);
?>